### PR TITLE
Update to 2.2

### PR DESCRIPTION
**Pull request by jochym**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jochym** [comment]
@conda-forge-admin please rerender

**Comment by jochym** [comment]
@brandon-rhodes Shell we build from the pypi tar or from github?

**Comment by brandon-rhodes** [comment]
> Shell we build from the pypi tar or from github?

The PyPI tar should always be the safest and most official choice.

**Comment by brandon-rhodes** [comment]
@jochym Amazing, you did it! Thanks for wrangling these feedstocks to make my libraries available to all the folks in the conda ecosystem.

**Pull request merged**
